import { ThemeProvider } from '@/components/theme-provider';
import './global.css';
import {NavigationMenuBar}from '@/components/nav-bar';

export const metadata = {
  title: 'Welcome to samurai',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
      <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <NavigationMenuBar />
            {children}
          </ThemeProvider>
      </body>
    </html>
  );
}
